### ISSUE TITLE
Change website meta data and image

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/website-documentation#13]

**Comment by mufassirkazi** [comment]
![ogimage_darkhomepage_1](https://user-images.githubusercontent.com/46087290/94782023-47648c80-03e8-11eb-859e-17cdca6676c3.png)

**Comment by mufassirkazi** [comment]
Favicon Title: SuperTokens - Open Source Auth :dizzy:

Title: SuperTokens - Open Source Auth with login and secure sessions
Subheading Copy: SuperTokens offers a highly secure and quick to implement open source solution that manages end to end authentication for you.
