### ISSUE TITLE
Pricing + Dashboard changes 

### ISSUE THREAD

**Issue by mufassirkazi** [supertokens/website-documentation#18]
For our open source auth solution we intend to do the following changes:

## Pricing page:
 - A dark themed pricing page that reflects that our on premises solution is free, no limits. Our SaaS based solution is free for 5K monthly active users, post which, we charge $29 / month on a subscription basis.
- Our list of features mainly categorised into login, session management and user management features
- A comparison chart between us and all other popular open source solutions
- Our pricing philosophy. Here we'll answer how we intend to make money thorough our solution

## SaaS Dashboard
- Removing instances completely as we no longer charge with respect to instances but on the number of monthly active users. 
- We'll have two environments namely: 1. Development Environment 2. Production Environment
- User can connect and edit configuration in development environment to test out SuperTokens 
- User can create a production environment and use it for free of cost up to 5K monthly active users. Once the limit is reached, we'll inform the user on the dashboard itself and via email to upgrade to our subscription plan. SuperTokens service will **_not_** be withdrawn in case of delay in payment up to 1 month

**Comment by rishabhpoddar** [comment]
@mufassirkazi can you upload the webflow file + provide zeplin links here?

**Comment by mufassirkazi** [comment]
[pricing-page-open-source-auth.webflow (6).zip](https://github.com/supertokens/website-documentation/files/5332567/pricing-page-open-source-auth.webflow.6.zip)

SaaS Dashboard design links: 
https://zpl.io/bWeo3yM
https://zpl.io/aXexRpE

**Comment by rishabhpoddar** [comment]
@mufassirkazi 
A few issues with the webflow:
- The see how we compare to other solutions is very important IMO. Right now it's collapsed which means it's not going to be seen..
- When hovering the mouse over the above text, the pointer doesnt change to a hand.
- The comparison chart is missing on mobile version. Is that intentional? If so, do i still remove it from the github readme?
- I would like to link to the comparison chart directly.. Can you make it in webflow so that if the URL has some query param, it shows the comparison chart by default?

**Comment by mufassirkazi** [comment]
-"See how we compare with other solutions" and "Our philosophy" both are of equal importance. The design has been done in such a way that a user scrolling should know that both exist. An expanded comparison table may result in our philosophy section being completely missed out by the user. We can check recordings or do an analytic even to see if people are interacting with the comparison chart. 
- Will change pointer to hand
- Yes, we won't have mobile/ tab version of comparison chart. And yes, please remove from readme too. Its too much information overload and horizontal scrolling.
- Didn't understand last point
-Try adding #comparison-chart to link to the comparison chart directly
[pricing-page-open-source-auth.webflow (7).zip](https://github.com/supertokens/website-documentation/files/5333189/pricing-page-open-source-auth.webflow.7.zip)

**Comment by rishabhpoddar** [comment]
> We can check recordings or do an analytic event to see if people are interacting with the comparison chart.

This never ends up happening. I believe that the comparison chart is far more important than the philosophy. But fine.

> Try adding #comparison-chart to link to the comparison chart directly

Are you telling me to do it? Or have you done it?

**Comment by mufassirkazi** [comment]
> Are you telling me to do it? Or have you done it?

I did it, it works for me. You have to upload the new webflow file that I sent in my previous message

**Comment by rishabhpoddar** [comment]
For testing, a few deviations from the design for the dashboard:
- Shown the version next to the environment - this is cause this helps them know which version of the SDKs they should use.
- Added "There is a limit of upto 100 concurrent users in this environment." for clarity.
- A few copy changes to remove redundant info in the production env area (before creating an instance)
- Removed the SLA button since we don't have one.

## Issues:
- "/pricing#comparison-chart" takes you to the comparison chart area, but it does not open it. Please auto open it

**Comment by mufassirkazi** [comment]
Okay. 

For the issue part, I'm not sure how to auto open. That's an interaction, and a query parameter can't trigger an interaction.

**Comment by rishabhpoddar** [comment]
Please learn how to do that in webflow and do it. That's the most basic use of JS. Thanks

**Comment by rishabhpoddar** [comment]
I have pushed to test.supertokens.io

@jscyo , @mufassirkazi , please test it out and lmk if any changes are required (apart from the "/pricing#comparison-chart" issue).

**Comment by jscyo** [comment]
alright, checking it out

**Comment by rishabhpoddar** [comment]
@mufassirkazi there is an issue in your comparison chart. It says "Use with server less". It should be "Use with serverless"

**Comment by mufassirkazi** [comment]
![Screen Shot 2020-10-08 at 1 47 27 PM](https://user-images.githubusercontent.com/46087290/95433356-71c8c380-096d-11eb-82e6-550215cba9d0.png)

In development environment:
- Small typo: There is a limit of upto 100 concurrent users -> There is a limit of **up to** 100 concurrent users
- The space below the "Create production environment" button should ideally be the same as below the "Connect" and "Edit configuration" buttons

Pricing page:

- Changed copy to serverless
- Had a bit of padding issue, sorted that.

New pricing page webflow file:
[pricing-page-open-source-auth.webflow (19).zip](https://github.com/supertokens/website-documentation/files/5346355/pricing-page-open-source-auth.webflow.19.zip)

**Comment by rishabhpoddar** [comment]
- The dashboard changes are not going to be done.. "upto" is correct imo, and the spacing change doesn't matter as such (it's not worth the effort to reverse engineer the css etc).

- Updated the pricing webflow page. Please check the pricing page again in all dimensions.

**Comment by rishabhpoddar** [comment]
@mufassirkazi 
Should we also remove the comparison chart from reader and link it to the pricing page? 

If we do that though, it will go to that section, but it will still be collapsed.

So please figure out how to uncollapse it in case the URL has #comparison-chart (or whatever that hash is).

**Comment by mufassirkazi** [comment]
Checked the pricing page. You can push it to production. @jscyo you can have a look also to check whether everything is proper. 

@rishabhpoddar Yes, I would like it if we link to the comparison chart from readme. I tried to see if I can uncollapse it in some way. I asked joel also and we tried adding some custom code, but it wasn't working. Will look into it when I have time.

**Comment by rishabhpoddar** [comment]
@mufassirkazi 
> Will look into it when I have time.
This never happens. Either spend some time figuring it now, else I can do it. It's straighforward via JS... You just need to know how to inject JS in webflow. Until this is done, I will not push it to production
